# Generated by Django 4.1.1 on 2022-10-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='broj_telefona',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
