# Generated by Django 3.0.14 on 2022-09-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_termin'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='broj_telefona',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='termin',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
