# Generated by Django 4.1.1 on 2022-11-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_slike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slike',
        ),
    ]
