# Generated by Django 4.1.1 on 2022-11-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_delete_slike'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
