# Generated by Django 3.0.14 on 2022-09-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20220919_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termin',
            name='broj_telefona',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
