# Generated by Django 3.0.14 on 2022-09-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20220920_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usluge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cena', models.CharField(max_length=15)),
            ],
        ),
    ]
