# Generated by Django 4.1.1 on 2022-11-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_termin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='broj_telefona',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
