# Generated by Django 4.1.1 on 2022-09-27 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_usluge'),
    ]

    operations = [
        migrations.AddField(
            model_name='usluge',
            name='duzina',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
