# Generated by Django 4.1.1 on 2022-09-27 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_usluge_duzina_alter_korisnik_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='usluga',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.usluge'),
        ),
    ]
