# Generated by Django 4.1.1 on 2022-12-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_korisnik_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
