# Generated by Django 4.1.1 on 2025-02-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_alter_korisnik_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='dugovanje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
