# Generated by Django 4.1.1 on 2022-09-27 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_frizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='frizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.frizer'),
        ),
        migrations.AlterField(
            model_name='termin',
            name='usluga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.usluge'),
        ),
    ]
