# Generated by Django 4.1.1 on 2025-02-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_korisnik_dugovanje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usluge',
            name='cena',
            field=models.IntegerField(max_length=15),
        ),
    ]
