# Generated by Django 4.1.1 on 2022-09-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_termin_frizer_alter_termin_usluga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termin',
            name='datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='termin',
            name='vreme',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
