# Generated by Django 4.1.1 on 2022-09-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_alter_termin_datum_alter_termin_vreme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frizer',
            name='name',
            field=models.CharField(default='Izaberite Frizera', max_length=250),
        ),
        migrations.AlterField(
            model_name='usluge',
            name='name',
            field=models.CharField(default='Izaberite Uslugu', max_length=250),
        ),
    ]
