# Generated by Django 4.1.1 on 2025-02-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_duznik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='dugovanje',
            field=models.IntegerField(default=0),
        ),
    ]
