# Generated by Django 4.1.1 on 2025-03-17 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_alter_korisnik_dugovanje'),
    ]

    operations = [
        migrations.AddField(
            model_name='duznik',
            name='datum_upisa',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
