# Generated by Django 4.1.1 on 2025-03-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_duznik_datum_upisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='poruka',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
