# Generated by Django 4.1.1 on 2022-10-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_alter_termin_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='uredjaj',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
