# Generated by Django 4.1.1 on 2022-10-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_termin_uredjaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='ime_prezime',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
