# Generated by Django 4.1.1 on 2025-05-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_termin_cena_termina'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='termin',
            unique_together=set(),
        ),
    ]
