# Generated by Django 4.1.1 on 2025-06-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='dodatne_usluge',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterUniqueTogether(
            name='termin',
            unique_together={('datum', 'vreme', 'frizer')},
        ),
    ]
