# Generated by Django 4.1.1 on 2025-06-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_termin_dodatne_usluge_alter_termin_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termin',
            name='dodatne_usluge',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
