# Generated by Django 4.2.23 on 2025-07-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0019_notification_push_sent_fcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usluge',
            name='cena',
            field=models.IntegerField(),
        ),
    ]
