# Generated by Django 4.2.23 on 2025-08-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0021_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='usluge',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='images/usluga/'),
        ),
    ]
