# Generated by Django 4.2.23 on 2025-08-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0022_usluge_slika'),
    ]

    operations = [
        migrations.AddField(
            model_name='frizer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
