# Generated by Django 4.2.23 on 2025-09-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0024_alter_fcmtoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Naslov banera')),
                ('text', models.TextField(max_length=500, verbose_name='Tekst banera')),
                ('start_date', models.DateTimeField(verbose_name='Početak prikazivanja')),
                ('end_date', models.DateTimeField(verbose_name='Kraj prikazivanja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banneri',
                'ordering': ['-created_at'],
            },
        ),
    ]
