# Generated by Django 4.2.23 on 2025-11-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0025_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='usluge',
            name='kategorija',
            field=models.CharField(choices=[('sisanje', 'Šišanje'), ('brada', 'Brada'), ('ostale_usluge', 'Ostale usluge'), ('vip_usluge', 'Vip usluge')], default='sisanje', max_length=50),
        ),
    ]
