# Generated by Django 4.2.23 on 2025-11-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0026_usluge_kategorija'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/gallery/', verbose_name='Slika')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Naslov')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Opis')),
                ('order', models.IntegerField(default=0, verbose_name='Redosled prikazivanja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slika iz galerije',
                'verbose_name_plural': 'Slike iz galerije',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
