# Generated by Django 4.2.23 on 2025-11-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0027_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='loyalty_appointment_count',
            field=models.IntegerField(default=0, help_text='Number of appointments counted toward loyalty program (every 15th is free)'),
        ),
    ]
