#!/bin/bash
# Setup ngrok for HTTPS access to local Django server

echo "Setting up ngrok for HTTPS access..."
echo ""
echo "1. Install ngrok if not already installed:"
echo "   brew install ngrok"
echo ""
echo "2. Start Django server:"
echo "   python3 manage.py runserver 127.0.0.1:8000"
echo ""
echo "3. In another terminal, start ngrok:"
echo "   ngrok http 8000"
echo ""
echo "4. Copy the HTTPS URL from ngrok (e.g., https://abc123.ngrok.io)"
echo ""
echo "5. Add the ngrok URL to CSRF_TRUSTED_ORIGINS in settings.py"
echo ""
echo "6. Access your site via the ngrok HTTPS URL"
echo ""
echo "This will give you HTTPS access that works with FCM!"