# Generated by Django 4.1.1 on 2022-11-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerija', '0002_alter_slike_kategorija'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slike',
            name='slika',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
