# Generated by Django 4.0.6 on 2024-06-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerija', '0003_alter_slike_slika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slike',
            name='kategorija',
            field=models.CharField(choices=[('krace-moderne', 'Kraće moderne'), ('duze-moderne', 'Duže moderne'), ('decije-frizure', 'Dečije frizure'), ('tribali', 'Tribali'), ('internet-frizure', 'Internet frizure'), ('ostale-usluge', 'Ostale usluge')], max_length=50),
        ),
    ]
